name: flutter_chat_mvvm
description: A simple chat application using MVVM architecture and Riverpod in Flutter.

publish_to: 'none' 

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/