// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs6u-u9iQ4_qWP8qyVDomu8YzWhn74g-o',
    appId: '1:629098486092:web:d3217af2ad453260a197e9',
    messagingSenderId: '629098486092',
    projectId: 'flashcard-6fdba',
    authDomain: 'flashcard-6fdba.firebaseapp.com',
    storageBucket: 'flashcard-6fdba.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_Zjp8ZMABr7dMA1jstCGLB91f-HHPzPE',
    appId: '1:629098486092:android:73242621772e8f43a197e9',
    messagingSenderId: '629098486092',
    projectId: 'flashcard-6fdba',
    storageBucket: 'flashcard-6fdba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbv3sQ7Oma92H6FoZcU4LjI02CaYSuGcg',
    appId: '1:629098486092:ios:150e645004b8dd8ca197e9',
    messagingSenderId: '629098486092',
    projectId: 'flashcard-6fdba',
    storageBucket: 'flashcard-6fdba.firebasestorage.app',
    iosBundleId: 'com.example.flashcardApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbv3sQ7Oma92H6FoZcU4LjI02CaYSuGcg',
    appId: '1:629098486092:ios:150e645004b8dd8ca197e9',
    messagingSenderId: '629098486092',
    projectId: 'flashcard-6fdba',
    storageBucket: 'flashcard-6fdba.firebasestorage.app',
    iosBundleId: 'com.example.flashcardApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs6u-u9iQ4_qWP8qyVDomu8YzWhn74g-o',
    appId: '1:629098486092:web:370b44e8e645fb1aa197e9',
    messagingSenderId: '629098486092',
    projectId: 'flashcard-6fdba',
    authDomain: 'flashcard-6fdba.firebaseapp.com',
    storageBucket: 'flashcard-6fdba.firebasestorage.app',
  );
}
